site_name: OutputKit
repo_url: https://github.com/nturpin0/UILibrary
nav:
  - Getting started: quickview.md
  - ml tags: menus.md
  - Component tags: tables.md
  - Shortcuts: examples.md
  - Showcase: credits.md
theme:
  name: readthedocs
