site_name: OutputKit
repo_url: https://github.com/nturpin0/UILibrary
nav:
  - Quickview: quickview.md
  - Menus: menus.md
  - Tables: tables.md
  - Examples: examples.md
  - Credits: credits.md
theme:
  name: readthedocs
