site_name: UILibrary
repo_url: https://github.com/nturpin0/UILibrary
nav:
  - Getting started: 'GettingStarted.md'
  - Quickview: 'quickview.md'
  - Tables: 'Tables.md'
  - Shortcuts: 'ExampleShortcuts.md'
  - Menus: 'Menus.md'
  - Thanks: 'credits.md'
theme:
  name: readthedocs
